"""Add Tasks model.

Revision ID: 27a246ee47df
Revises: aac8194aba75
Create Date: 2026-09-27 17:25:48.835919

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27a246ee47df"
down_revision: str | Sequence[str] | None = "aac8194aba75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS tasks")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("created", "active", "canceled", "in_progress", "need_review", "completed", name="task_status"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("responsible_id", sa.Uuid(), nullable=False),
        sa.Column("observer_ids", sa.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("executor_ids", sa.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("estimated_minutes >= 0", name="check_estimated_minutes_ge_zero"),
        sa.PrimaryKeyConstraint("id"),
        schema="tasks",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task", schema="tasks")
    # ### end Alembic commands ###
    op.execute("DROP TYPE task_status")

    op.execute("DROP SCHEMA IF EXISTS tasks")
