"""Add tasks task estimated_minutes max value constraint

Revision ID: 3f90e3addde8
Revises: ecb73c140b53
Create Date: 2026-10-05 19:05:35.623855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f90e3addde8'
down_revision: Union[str, Sequence[str], None] = 'ecb73c140b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_estimated_minutes_le_max_value', 'task', 'estimated_minutes <= 525600', schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_estimated_minutes_le_max_value', 'task', schema='tasks', type_='check')
    # ### end Alembic commands ###
