"""create org models.

Revision ID: aac8194aba75
Revises: 023e8b878434
Create Date: 2026-09-14 18:01:43.407461

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.modules.org.models.types import LtreeType

# revision identifiers, used by Alembic.
revision: str = "aac8194aba75"
down_revision: str | Sequence[str] | None = "023e8b878434"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS org")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="org",
    )
    op.create_table(
        "struct_adm",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("path", LtreeType(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("director_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "path", name="unique_pair_company_id_path"),
        schema="org",
    )
    op.create_index(
        "index_struct_adm_path_gist", "struct_adm", ["path"], unique=False, schema="org", postgresql_using="gist"
    )
    op.create_table(
        "struct_adm_positions",
        sa.Column("struct_adm_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["org.position.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["struct_adm_id"], ["org.struct_adm.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("position_id"),
        schema="org",
    )
    op.create_table(
        "users_positions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["org.position.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "position_id", name="unique_pair_user_id_position_id"),
        schema="org",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_positions", schema="org")
    op.drop_table("struct_adm_positions", schema="org")
    op.drop_index("index_struct_adm_path_gist", table_name="struct_adm", schema="org", postgresql_using="gist")
    op.drop_table("struct_adm", schema="org")
    op.drop_table("position", schema="org")
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS org")
