"""empty message.

Revision ID: bb05935ef7b2
Revises: e622005fda75
Create Date: 2026-08-19 20:16:10.060077

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb05935ef7b2"
down_revision: str | Sequence[str] | None = "e622005fda75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invite", sa.Column("token_hash", sa.String(), nullable=False), schema="auth")
    op.add_column("invite", sa.Column("used_at", sa.DateTime(timezone=True), nullable=True), schema="auth")
    op.add_column("invite", sa.Column("recipient_email", sa.String(), nullable=False), schema="auth")
    op.alter_column(
        "invite",
        "expired_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        schema="auth",
    )
    op.alter_column("invite", "account_id", existing_type=sa.INTEGER(), nullable=True, schema="auth")
    op.drop_constraint(op.f("invite_token_key"), "invite", schema="auth", type_="unique")
    op.create_unique_constraint(None, "invite", ["token_hash"], schema="auth")
    op.drop_column("invite", "token", schema="auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invite", sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False), schema="auth")
    op.drop_constraint(None, "invite", schema="auth", type_="unique")
    op.create_unique_constraint(
        op.f("invite_token_key"), "invite", ["token"], schema="auth", postgresql_nulls_not_distinct=False
    )
    op.alter_column("invite", "account_id", existing_type=sa.INTEGER(), nullable=False, schema="auth")
    op.alter_column(
        "invite",
        "expired_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        schema="auth",
    )
    op.drop_column("invite", "recipient_email", schema="auth")
    op.drop_column("invite", "used_at", schema="auth")
    op.drop_column("invite", "token_hash", schema="auth")
    # ### end Alembic commands ###
